name: upload

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  copy-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
    
      - name: Copy PR templates
        run: |
          cp -r pr-templates/* $GITHUB_WORKSPACE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Workflow B in Repository B
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.PAT_TOKEN_B }}  # Personal Access Token for Repository B
          script: |
            const { owner, repo } = context.repo;
            await octokit.actions.createWorkflowDispatch({
              owner: 'raivenhart',  # Replace with your organization name
              repo: 'new-demo',         # Replace with the name of Repository B
              workflow_id: 'sync-template.yml'  # Replace with the name of Workflow B
            })